<a href="https://colab.research.google.com/github/gakbn/ESCB-AngelGabrielAndradeAmezcua/blob/main/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dfSucio=pd.read_csv("dataset_sucio_practica.csv")

In [ ]:
dfSucio.shape

(125, 8)

In [ ]:
dfSucio.head()

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
1,2,NaN,35.0,asimmons@garza.com,España,NaN,2026-05-04,No
2,3,George Burke,40.0,mcclainerin@gmail.com,Argentina,NaN,2026-01-27,NaN
3,4,Joyce Williams,30.0,correo_invalido,Argentina,25000.0,2025-02-23,No
4,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí

In [ ]:
dfSucio.tail()

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
120,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
121,2,NaN,35.0,asimmons@garza.com,España,NaN,2026-05-04,No
122,3,George Burke,40.0,mcclainerin@gmail.com,Argentina,NaN,2026-01-27,NaN
123,4,Joyce Williams,30.0,correo_invalido,Argentina,25000.0,2025-02-23,No
124,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí

In [ ]:
dfSucio.describe()

               id        edad       salario
count  125.000000  110.000000    107.000000
mean    58.200000   43.945455  14093.457944
std     35.906465   47.489803   8825.918852
min      1.000000   -5.000000  -1000.000000
25%     27.000000   22.750000  12000.000000
50%     58.000000   30.000000  15000.000000
75%     89.000000   40.000000  18000.000000
max    120.000000  150.000000  25000.000000

In [ ]:
dfSucio[dfSucio["id"].isin([29,55,58])]

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
28,29,Teresa Ramos,22.0,rileyraymond@hotmail.com,México,-1000.0,2025-08-29,NaN
54,55,John Lewis,NaN,rodriguezbrett@yahoo.com,México,-1000.0,2024-07-03,NaN
57,58,Michael Barajas,40.0,antoniocox@hotmail.com,España,15000.0,2026-05-02,NaN

In [ ]:
#Genereamos una copia
dfCopy = dfSucio.copy()

In [ ]:
dfSucio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              125 non-null    int64
 1   nombre          116 non-null    object
 2   edad            110 non-null    float64
 3   correo          125 non-null    object
 4   pais            82 non-null     object
 5   salario         107 non-null    float64
 6   fecha_registro  125 non-null    object
 7   activo          90 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 7.9+ KB